name: Building TWRP

on:
  workflow_dispatch:
    inputs:
        tagName:
            description: 'new tag name'     
            required: true
            default: ''
        tagBody:
            description: 'tag message'     
            required: false
            default: 'This is a pre-release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main

       - name: Recovery Compilation
         uses: crazo7924/Recovery-Compiler@beta
         env:
           MANIFEST: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11"
           DT_LINK: "https://github.com/crazo7924/android_device_realme_RMX3241.git"
           VENDOR: "realme"
           CODENAME: "RMX3241"
           TARGET: "recoveryimage"
           FLAVOR: "eng"
           TZ: "Asia/Kolkata"

       - name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ github.event.inputs.tagName }}
           release_name: Release ${{ github.event.inputs.tagName }}
           body: ${{ github.event.inputs.tagBody }}
           draft: false
           prerelease: true
           
       - name: Upload Release Asset
         id: upload-release-asset 
         uses: xresloader/upload-to-github-release@master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           file: "${BuildPath}/out/target/product/${CODENAME}/recovery.img"
           release_id: ${{ steps.create_release.outputs.id }}
           tag_name: ${{ github.event.inputs.tagName }}
           overwrite: true
           verbose: false
           draft: false
           prerelease: true
